import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import {
  AuthProvider,
  ModalProvider,
  QueryProvider,
  SWRProvider,
  ThemeProvider,
  RealtimeProvider,
  LoadingProvider,
} from "@/components/providers";
import { cn } from "@/lib/utils";

// ✅ Đặt tên biến đúng với font đang dùng
const font = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DisMess",
  description: "Generated by create next app",
  icons: {
    icon: "/logoapp.webp", // hoặc
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(font.variable, "antialiased bg-white dark:bg-[#313338]")}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <LoadingProvider>
            <RealtimeProvider>
              <SWRProvider>
                <ModalProvider>
                  <QueryProvider>
                    <AuthProvider>{children}</AuthProvider>
                  </QueryProvider>
                </ModalProvider>
              </SWRProvider>
            </RealtimeProvider>
          </LoadingProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
