import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import {
  AuthProvider,
  ModalProvider,
  QueryProvider,
  SWRProvider,
  ThemeProvider,
} from "@/components/providers";
import { cn } from "@/lib/utils";
import { RealtimeProvider } from "@/components/providers/realtime-provider";

// ✅ Đặt tên biến đúng với font đang dùng
const font = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "DisMess",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          font.variable,
          "antialiased bg-white dark:bg-[#313338]"
        )}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ModalProvider>
          <SWRProvider>
            
            <QueryProvider>
              <AuthProvider><RealtimeProvider>{children}</RealtimeProvider></AuthProvider>
                
            </QueryProvider>
          </SWRProvider>
          </ModalProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
